import { TopBar } from '@/components/ui/TopBar'
import '../styles/globals.css'
import type { Metadata, Viewport } from 'next'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'
import { ThemeProvider } from './ThemeProvider'
import AuthChecker from './AuthChecker'

import { GeistSans, GeistMono } from 'geist/font'

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  userScalable: false,
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full w-full" suppressHydrationWarning>
      <body className={cn(GeistMono.className, 'h-full w-full')}>
        <AuthChecker />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div
            vaul-drawer-wrapper=""
            className="flex h-full max-h-full w-full flex-col px-safe pt-safe landscape:px-0"
          >
            <header>
              <TopBar />
            </header>
            <main className="flex-1 overflow-auto landscape:pl-safe">
              {children}
            </main>
            <Toaster />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
